config/routes.rb
Metrics::Application.routes.draw do
  
  resources :grades

  resources :evaluations

  resources :grading_scales

  resources :report_definitions

  match 'coffee' => 'projects#coffee'
  
  resources :metric_snapshots

  resources :constants

  resources :operators

  resources :metrics

  resources :formula_items

  resources :formulas

  resources :projects

  resources :reports

  devise_for :users

  root :to => "reports#index"

end

app/models/report_definition.rb
class ReportDefinition < ActiveRecord::Base
  has_many :project_report_definitions
  has_many :projects, :through => :project_report_definitions
  has_many :evaluations
  accepts_nested_attributes_for :evaluations, :projects,:project_report_definitions, :allow_destroy => true
end

app/controllers/report_definitions_controller.rb
class ReportDefinitionsController < ApplicationController
  # GET /report_definitions
  # GET /report_definitions.xml
  def index
    @report_definitions = ReportDefinition.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @report_definitions }
    end
  end

  # GET /report_definitions/1
  # GET /report_definitions/1.xml
  def show
    @report_definition = ReportDefinition.find(params[:id])
    @date = params[:date].nil? ? Time.now : Time.parse(params[:date]) 
    @evaluations =  @report_definition.evaluations 
    @projects =  @report_definition.projects

    respond_to do |format|
      to_render = {:id => @report_definition.id , :evaluations => @evaluations.map{|e| e.to_hash }, :projects => @projects}
      
      format.html # show.html.erb
      format.xml  { render :xml => to_render }
      format.json { render :json => to_render }
    end
  end

  # GET /report_definitions/new
  # GET /report_definitions/new.xml
  def new
    @report_definition = ReportDefinition.new
    @report_definition.project_report_definitions.build
    @report_definition.evaluations.build 

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @report_definition }
    end
  end

  # GET /report_definitions/1/edit
  def edit
    @report_definition = ReportDefinition.find(params[:id])
  end

  # POST /report_definitions
  # POST /report_definitions.xml
  def create
    @report_definition = ReportDefinition.new(params[:report_definition])

    respond_to do |format|
      if @report_definition.save
        format.html { redirect_to(@report_definition, :notice => 'Report definition was successfully created.') }
        format.xml  { render :xml => @report_definition, :status => :created, :location => @report_definition }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @report_definition.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /report_definitions/1
  # PUT /report_definitions/1.xml
  def update
    @report_definition = ReportDefinition.find(params[:id])

    respond_to do |format|
      if @report_definition.update_attributes(params[:report_definition])
        format.html { redirect_to(@report_definition, :notice => 'Report definition was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @report_definition.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /report_definitions/1
  # DELETE /report_definitions/1.xml
  def destroy
    @report_definition = ReportDefinition.find(params[:id])
    @report_definition.destroy

    respond_to do |format|
      format.html { redirect_to(report_definitions_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/report_definitions_helper.rb
module ReportDefinitionsHelper

  def cell_id(project,evaluation)
    "project_#{project.id}_evaluation_#{evaluation.id}"
  end
  
  def identify(*records)
    records.map{|r| "#{r.class.name.downcase}_#{r.id}"}.join('_')
  end

  def date_format(time)
    time.strftime '%B %e, %Y' 
  end

  def formula_graph_id(formula)
    "formula_graph_#{formula.id}"
  end


end

app/views/report_definitions/_form.html.erb
  <script>



    function Nested(selected){
      this.size = selected.length
      this.last = jQuery(selected.get(this.size - 1))
      this.template = jQuery(selected.get(0)).clone();
    }

    Nested.prototype.add = function(){
      var new_item = this.template.clone()
      var form_items = new_item.find('input,select,textarea');
      var that = this;
      form_items.each(function(){
        var attr = jQuery(this).attr('name');
        if (typeof attr !== 'undefined' && attr !== false) {
          jQuery(this).attr('name', attr.replace(/\d+/, that.size + 1));    
          jQuery(this).removeAttr('id')
        }
      });
      this.last.after(new_item);
      this.last = new_item;
      this.size = this.size + 1;
    }

    $.fn.nested = function(options) {
      var defaults = {
        addButton: '#add_button'
      }
      var options = $.extend(defaults, options); 
      var nested = new Nested(this);
      jQuery(options.addButton).click(function(e){ e.preventDefault(); nested.add(); });
    };

    jQuery(document).ready(function(){
      //jQuery('select').chosen();
      jQuery('#projects .nested').nested({addButton:'#projects .add'});
      jQuery('#evaluations .nested').nested({addButton:'#evaluations .add'});

      jQuery('.remove').live('click',function(){
        var checkbox = jQuery(this);
        var siblings = checkbox.siblings();
        var isChecked = checkbox.is(':checked');
        var parent = checkbox.parent();
        if(isChecked){
          parent.css('background-color', '#ddd');
          siblings.each(function(){ jQuery(this).css({'background-color': '#FF4040', 'color': '#eee'}); });
        }else{
          parent.css('background-color', 'transparent');
          siblings.each(function(){ jQuery(this).css({'background-color': 'transparent', 'color': 'inherit'}); });
        }
      });
    });

  </script>

<%= form_for(@report_definition) do |f| %>
  <% if @report_definition.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@report_definition.errors.count, "error") %> prohibited this report_definition from being saved:</h2>

      <ul>
      <% @report_definition.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <fieldset id=projects><legend>Projects</legend>
    <%= f.fields_for :project_report_definitions do |project_form| %>
    <fieldset class='nested'>
      <%= project_form.select(:project_id, Project.all.map{|p| [p.name, p.id] }) %>
      <%= project_form.check_box '_destroy', {:class => 'remove'} %>
      <%= project_form.label '_destroy', 'Remove' %>
    </fieldset>
    <% end %>
    <a href="#" class="add">add_project</a>
  </fieldset>
 
  <fieldset id="evaluations"><legend>Evaluations</legend>
    <%= f.fields_for :evaluations do |evaluation| %>
    <div class='nested'>
      <%= evaluation.label :formula %>
      <%= evaluation.select(:formula_id, Formula.all.map{|p| [p.name, p.id] }) %>
      <%= evaluation.label :grading_scale %>
      <%= evaluation.select(:grading_scale_id, GradingScale.all.map{|p| [p.name, p.id] }) %>
      <%= evaluation.check_box '_destroy', {:class => 'remove'} %>
      <%= evaluation.label '_destroy', 'Remove' %>
    </div>
    <% end %>
    <a href="#" class="add">add_evaluation</a>
  </fieldset>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/report_definitions/edit.html.erb
<h1>Editing report_definition</h1>

<%= render 'form' %>

<%= link_to 'Show', @report_definition %> |
<%= link_to 'Back', report_definitions_path %>

app/views/report_definitions/index.html.erb
<h1>Listing report_definitions</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @report_definitions.each do |report_definition| %>
  <tr>
    <td><%= report_definition.name %></td>
    <td><%= link_to 'Show', report_definition %></td>
    <td><%= link_to 'Edit', edit_report_definition_path(report_definition) %></td>
    <td><%= link_to 'Destroy', report_definition, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Report definition', new_report_definition_path %>

app/views/report_definitions/new.html.erb
<h1>New report_definition</h1>

<%= render 'form' %>

<%= link_to 'Back', report_definitions_path %>

app/views/report_definitions/show.html.erb
<% content_for :head do %>
  <%= javascript_include_tag 'highcharts' %>
<% end %>

<style>
  /*.ui-progressbar{ background-image: url(images/pbar-ani.gif); }*/
  td:hover{
    background-color:#ddd;
  }
  th{
    text-align:left;
  }
  th .formula{
    font-size:9pt;
    font-weight:normal;
  }
  .error {
    background-color:#ED8593;
  }
  .stale{
    background-color:#F2E194;
  }
  .template{
    display:none;
  }
  .hide{ display:none; }
  .popup,tr > td.calculated:nth-child(2) .popup{
    margin-left:60px;
    margin-top:-5px;
    padding:10px;
    display:none;
    background-color:#fff;
    position:absolute;
    border:1px solid #ddd;
    -moz-border-radius: 15px;
    border-radius: 15px;
    width:400px;
    z-index:99;
  }
  tr > td:last-child .popup{
    margin-left:-250px;
  }
  fieldset{
    -moz-border-radius: 15px;
    border-radius: 15px;
    border:1px solid #ddd;
  }
</style>

<script>
  function createGraph(id,title,subtitle,yaxis){
       var chart = new Highcharts.Chart({
      chart: {
         renderTo:id,
         type: 'spline'
      },
      title: {
         text:title 
      },
      subtitle: {
         text: subtitle   
      },
      xAxis: {
         type: 'datetime',
         dateTimeLabelFormats: { // don't display the dummy year
            month: '%e. %b',
            year: '%b'
         }
      },
      yAxis: {
         title: {
            text: yaxis
         }
      },
      tooltip: {
         formatter: function() {
                   return Highcharts.dateFormat('%b %m, %Y', this.x) +' - '+ this.y;
         }
      }
   }); 
     return chart;       
  }
</script>
<script>
  function random(min,max){
    return Math.floor(Math.random() * (max - min + 1)) + min;
  }
  function increment(bar,max,speed){
    var interval = null;
    var animate = function(){
      value = bar.progressbar("value") + random(0,5);
      if(value > 100 ){
        bar.progressbar({value:100});
      }else{
        bar.progressbar({value:value});
      }
      if(value >= max){
        clearInterval(interval);
      }
    }
    interval = setInterval(animate,speed);
  } 

  function Cell(jqSelected, project_id,evaluation_id,formula_id){
    this.jqSelected = jqSelected;
    this.formula_id = formula_id;
    this.project_id = project_id;
    this.evaluation_id = evaluation_id;

  }

  Cell.prototype.calculate = function(){
    var that = this;
    this.template = jQuery('#cell_template').clone().removeAttr('id').removeClass('template');
    var url = '/evaluations/' + that.evaluation_id + '.json?project_id=' + that.project_id + '&datetime=' + escape('<%= @date.iso8601 %>');

    jQuery.ajax({
      url:url,
      beforeSend:function(){that.beginToSpin();},
      success:function(data){ that.success(data);},
      error:function(xhr){ that.error(xhr.message);},
      dataType:'json' 
    });
  }

  Cell.prototype.beginToSpin = function(){
    var value = 0;
    var progressbar = this.jqSelected.progressbar({value:value}); 
    increment(progressbar,random(40,60),random(100,300));
  }
  Cell.prototype.stopSpinning = function(callback){
      var that = this;
      increment(this.jqSelected,100,50);
      this.jqSelected.progressbar({complete:function(){
        that.jqSelected.progressbar('destroy');
        that.jqSelected.text('');
        that.jqSelected.removeClass('ui-progressbar ui-widget-content');
        callback.call();
      }});
  }

  Cell.prototype.success = function(data, statua){
      var that = this;
      that.stopSpinning(function(){
        that.display(data); 
      });
  }


  Cell.prototype.display = function(data){
    function snapshotFromTemplate(snapshot){
      var template = jQuery('#snapshot_template').clone().removeAttr('id').removeClass('template');
      if(typeof(snapshot.metric_snapshot) !== 'undefined'){
        var snap = snapshot.metric_snapshot;
        if(snap.value == null){
          template.addClass('error');
        }
        else if(snapshot.is_stale){
          template.addClass('stale');
        }
        template.find('.is_stale').text(snapshot.is_stale);  
        template.find('.created_at').text(new Date(snap.created_at).toLocaleString());
        template.find('.updated_at').text(new Date(snap.updated_at).toLocaleString());
        template.find('.value').text(snap.value);
        template.find('.datetime').text(new Date(snap.datetime).toLocaleString());
        template.find('.metric').text(snapshot.metric_name);
        template.find('.id').text(snap.id);
      }else{
        template.find('.value').text('null');
        template.addClass('error');
      }
      return template;
    }
    var that = this;
    var template = this.template;

    template.find('.evaluated_string').text(data.calculated_string);

    if(data.isSuccess){
      template.find('.value').text(data.value + '/' + data.grade.grade.name );
      if(data.stale_snapshots.length > 0){ 
        template.addClass('stale'); 
      }
    }else if(!data.isSuccess){ 
      template.prepend(data.message);
      template.addClass('error'); 
    }


    jQuery(data.snapshots).each(function(){
      var snapshotTemplate = snapshotFromTemplate(this);  
      template.find('.snapshots').append(snapshotTemplate);
    });

    that.jqSelected.append(template);
  }

  Cell.prototype.error = function(message){
      var that = this;
      var data = {
        isSuccess:false,
        message:message,
        snapshots:[],
        stale_snapshots:[]
      };
      that.stopSpinning(function(){
        that.display(data); 
      });
  }

  jQuery(document).ready(function(){
        jQuery('td').live('mouseover mouseout',function(e){
          if(jQuery(this).has('.popup')){
            var popup = jQuery(this).find('.popup');
            if(e.type =="mouseover"){
              popup.show();
            }else{
              popup.hide();
            }
          }
        });
        var cell;
        <% @report_definition.projects.each do |project| %>
          <% @evaluations.each do |evaluation| %>
            cell = new Cell(jQuery('#<%= cell_id(project,evaluation) %>'), '<%= project.id %>', '<%= evaluation.id %>', '<%= evaluation.formula.id %>');
            cell.calculate();
          <% end %>
        <% end %>


      //graphs
    jQuery.ajax({
      url:"<%= report_definition_path(@report_definition.id) %>",
      //beforeSend:function(){that.beginToSpin();},
      success:function(report_def){ 
        function evaluation_id(evaluation){
          return "evaluation_graph_" + evaluation.id;
        }
        var jq_graphs = jQuery('#graphs');
        var graph_template = jQuery("#graph_template").clone().removeAttr('id').removeClass('template');
        jQuery.each(report_def.evaluations,function(idx,evaluation){
          var jq_graph = graph_template.clone(); 
          jq_graph.attr('id', evaluation_id(evaluation)); 
          jq_graphs.append(jq_graph);
          var chart = createGraph(jq_graph.attr('id'),evaluation.formula.name, evaluation.formula.formula, evaluation.formula.name);
          jQuery.each(report_def.projects,function(idx_proj, project_wrapper){
            var chartGraph = chart;
            var project_wrapper = project_wrapper;
            var that = this;
           jQuery.ajax({dataType:'json',url:"/evaluations/" + evaluation.id +".json?project_id="+ project_wrapper.project.id + "&all=true&numMonths=5",
              success:function(calculations){
                
                var data = [];
                jQuery.each(calculations,function(i,calc){ 
                  var date =  Date.UTC(calc.date.year,calc.date.month,calc.date.day) 
                  var val = calc.value;
                  data.push([date,val]);
                 });
                chart.addSeries({
                    name:project_wrapper.project.name,
                    data:data 
                },true,null);
              }
            });
          }); 
        });
      },
      //error:function(xhr){ that.error(xhr.message);},
      dataType:'json' 
    });
         
  });
</script>


<p id="notice"><%= notice %></p>

<div id="cell_template" class="template"> 
  <div><span class="label hide">value:</span><span class="value"></span></div>
  <div class="popup">
    calculation:<div class="evaluated_string"></div>
    <fieldset class="snapshots"><legend>metrics used in calculation</legend></fieldset>
  </div>
</div>

  <fieldset id="snapshot_template" class="snapshot template"><legend>snapshot</legend>
  <div>metric:<span class="metric"></span></div>
  <div>value: <span class="value"></span></div>
  <div class="hide">stale?: <span class="is_stale"></span></div>
  <div>measured on:<span class="datetime"></span></div>
  <div class="hide">created at: <span class="created_at"></span></div>
  <div>last synchronized: <span class="updated_at"></span></div>
  <div class="hide">id:<span class="id"></span></div>
  </fieldset>

<h1><%= @report_definition.name %> </h1>
<h2>
<%= link_to '<', report_definition_path(@report_definition, :date => @date - 1.day) %>
<%= date_format @date %>
<% if(@date.today?) %>
>
<% else %>
  <%= link_to '>', report_definition_path(@report_definition, :date => @date + 1.day) %>
<% end %>
</h2>

<% evaluations =  @report_definition.evaluations %>
<table> 
  <thead>
    <tr>
      <th>Projects</th>
      <% evaluations.each do |evaluation| %>
        <th id="<%= identify(evaluation,evaluation.formula) %>">
          <%= evaluation.formula.name %>
          <div class="formula"><span class="label hide">Formula:</span><%= evaluation.formula.to_s %></div>
        </th>
      <% end %>
    </tr>
  </thead>
  <tbody>
      <% @report_definition.projects.each do |project| %>
        <tr>
          <td id="<%= identify(project) %>" class="project"><%= project.name %></td>
          <% evaluations.each do |evaluation| %>
           <td id="<%= cell_id(project,evaluation) %>" class="calculated"> </td> 
          <% end %>
        </tr>
      <% end %>
  </tbody>
</table>


<div id="graphs">
    <div id="graph_template" class="template" height="200" width="400" ></div>
</div>

<%= link_to 'Edit', edit_report_definition_path(@report_definition) %> |
<%= link_to 'Back', report_definitions_path %>
<img src="http://naivepagetracker.heroku.com/websites/6/visit.gif" /> 