config/routes.rb
Metrics::Application.routes.draw do
  
  resources :grades

  resources :evaluations

  resources :grading_scales

  resources :report_definitions

  match 'coffee' => 'projects#coffee'
  
  resources :metric_snapshots

  resources :constants

  resources :operators

  resources :metrics

  resources :formula_items

  resources :formulas

  resources :projects

  resources :reports

  devise_for :users

  root :to => "reports#index"

end

app/models/metric_snapshot.rb
class MetricSnapshot < ActiveRecord::Base
  belongs_to :project
  belongs_to :metric
  
  def as_json(options={})
    result = super()
    result[:is_stale] = stale?
    result[:metric_name] = metric.name
    result
  end

  def stale?
    datetime < Time.now - 3.day &&  updated_at < Time.now - 1.day
  end
    
  def self.update_timestamps(snapshots)
    snapshots.each do |snapshot|
      unless snapshot.nil?
        snapshot.updated_at = Time.now
        snapshot.save
      end
    end
  end

  def self.stale?(snapshots)
    is_stale = false
    snapshots.each do |s|
      if ( s.nil? || s.stale? ) #TODO double check the logic here
        is_stale = true
        break
      end
    end
    is_stale
  end


end

app/controllers/metric_snapshots_controller.rb
class MetricSnapshotsController < ApplicationController
  # GET /metric_snapshots
  # GET /metric_snapshots.xml
  def index
    @metric_snapshots = MetricSnapshot.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @metric_snapshots }
    end
  end

  # GET /metric_snapshots/1
  # GET /metric_snapshots/1.xml
  def show
    @metric_snapshot = MetricSnapshot.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @metric_snapshot }
    end
  end

  # GET /metric_snapshots/new
  # GET /metric_snapshots/new.xml
  def new
    @metric_snapshot = MetricSnapshot.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @metric_snapshot }
    end
  end

  # GET /metric_snapshots/1/edit
  def edit
    @metric_snapshot = MetricSnapshot.find(params[:id])
  end

  # POST /metric_snapshots
  # POST /metric_snapshots.xml
  def create
    @metric_snapshot = MetricSnapshot.new(params[:metric_snapshot])

    respond_to do |format|
      if @metric_snapshot.save
        format.html { redirect_to(@metric_snapshot, :notice => 'Metric snapshot was successfully created.') }
        format.xml  { render :xml => @metric_snapshot, :status => :created, :location => @metric_snapshot }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @metric_snapshot.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /metric_snapshots/1
  # PUT /metric_snapshots/1.xml
  def update
    @metric_snapshot = MetricSnapshot.find(params[:id])

    respond_to do |format|
      if @metric_snapshot.update_attributes(params[:metric_snapshot])
        format.html { redirect_to(@metric_snapshot, :notice => 'Metric snapshot was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @metric_snapshot.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /metric_snapshots/1
  # DELETE /metric_snapshots/1.xml
  def destroy
    @metric_snapshot = MetricSnapshot.find(params[:id])
    @metric_snapshot.destroy

    respond_to do |format|
      format.html { redirect_to(metric_snapshots_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/metric_snapshots_helper.rb
module MetricSnapshotsHelper
end

app/views/metric_snapshots/_form.html.erb
<%= form_for(@metric_snapshot) do |f| %>
  <% if @metric_snapshot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@metric_snapshot.errors.count, "error") %> prohibited this metric_snapshot from being saved:</h2>

      <ul>
      <% @metric_snapshot.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :metric_id %><br />
    <%= f.text_field :metric_id %>
  </div>
  <div class="field">
    <%= f.label :project_id %><br />
    <%= f.text_field :project_id %>
  </div>
  <div class="field">
    <%= f.label :value %><br />
    <%= f.text_field :value %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/metric_snapshots/edit.html.erb
<h1>Editing metric_snapshot</h1>

<%= render 'form' %>

<%= link_to 'Show', @metric_snapshot %> |
<%= link_to 'Back', metric_snapshots_path %>

app/views/metric_snapshots/index.html.erb
<h1>Listing metric_snapshots</h1>

<table>
  <tr>
    <th>Metric</th>
    <th>Project</th>
    <th>Value</th>
    <th>Date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @metric_snapshots.each do |metric_snapshot| %>
  <tr>
    <td><%= metric_snapshot.metric_id %></td>
    <td><%= metric_snapshot.project_id %></td>
    <td><%= metric_snapshot.value %></td>
    <td><%= metric_snapshot.date %></td>
    <td><%= link_to 'Show', metric_snapshot %></td>
    <td><%= link_to 'Edit', edit_metric_snapshot_path(metric_snapshot) %></td>
    <td><%= link_to 'Destroy', metric_snapshot, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Metric snapshot', new_metric_snapshot_path %>

app/views/metric_snapshots/new.html.erb
<h1>New metric_snapshot</h1>

<%= render 'form' %>

<%= link_to 'Back', metric_snapshots_path %>

app/views/metric_snapshots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Metric:</b>
  <%= @metric_snapshot.metric_id %>
</p>

<p>
  <b>Project:</b>
  <%= @metric_snapshot.project_id %>
</p>

<p>
  <b>Value:</b>
  <%= @metric_snapshot.value %>
</p>

<p>
  <b>Date:</b>
  <%= @metric_snapshot.date %>
</p>


<%= link_to 'Edit', edit_metric_snapshot_path(@metric_snapshot) %> |
<%= link_to 'Back', metric_snapshots_path %>